# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  allure: ayte/allure@0.1.3

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - allure/install:
          version: 2.14.0
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - allure/report

workflows:
  sample: 
    jobs:
      - build-and-test
